"""empty message

Revision ID: 78c07974b9f6
Revises: 9be5058c713f
Create Date: 2017-09-12 21:17:30.792695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c07974b9f6'
down_revision = '9be5058c713f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsor', sa.Column('url', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsor', 'url')
    # ### end Alembic commands ###
