"""empty message

Revision ID: bdcc7cd69cd4
Revises: 50bdc2671dbe
Create Date: 2017-08-20 18:58:52.478500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcc7cd69cd4'
down_revision = '50bdc2671dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.alter_column('user', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'school_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
