"""empty message

Revision ID: f9f022c85739
Revises: 78c07974b9f6
Create Date: 2017-09-13 17:34:44.549895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9f022c85739'
down_revision = '78c07974b9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_in',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_challenge_id'), 'check_in', ['challenge_id'], unique=False)
    op.create_table('check_in_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_in_id'], ['check_in.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_question_check_in_id'), 'check_in_question', ['check_in_id'], unique=False)
    op.create_table('check_in_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_in_question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['check_in_question_id'], ['check_in_question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_in_answer_check_in_question_id'), 'check_in_answer', ['check_in_question_id'], unique=False)
    op.create_index(op.f('ix_check_in_answer_user_id'), 'check_in_answer', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_in_answer_user_id'), table_name='check_in_answer')
    op.drop_index(op.f('ix_check_in_answer_check_in_question_id'), table_name='check_in_answer')
    op.drop_table('check_in_answer')
    op.drop_index(op.f('ix_check_in_question_check_in_id'), table_name='check_in_question')
    op.drop_table('check_in_question')
    op.drop_index(op.f('ix_check_in_challenge_id'), table_name='check_in')
    op.drop_table('check_in')
    # ### end Alembic commands ###
