"""empty message

Revision ID: fe95971610b1
Revises: d55141a9af51
Create Date: 2017-09-10 19:06:51.078987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe95971610b1'
down_revision = 'd55141a9af51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_challenge_slug', table_name='challenge')
    op.create_index(op.f('ix_challenge_slug'), 'challenge', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_slug'), table_name='challenge')
    op.create_index('ix_challenge_slug', 'challenge', ['slug'], unique=True)
    # ### end Alembic commands ###
